### ISSUE TITLE
Cant run this project by following the instructions

### ISSUE THREAD

**Issue by liuchengyiu** [mbchang/data-driven-characters#9]
Traceback (most recent call last):
  File "/home/wanchengquan/.conda/envs/character_e/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/wanchengquan/data-driven-characters/app.py", line 7, in <module>
    from data_driven_characters.character import generate_character_definition, Character
  File "/home/wanchengquan/data-driven-characters/data_driven_characters/character.py", line 8, in <module>
    from data_driven_characters.chains import FitCharLimit, define_description_chain
  File "/home/wanchengquan/data-driven-characters/data_driven_characters/chains.py", line 45, in <module>
    class FitCharLimit(Chain):
  File "/home/wanchengquan/.conda/envs/character_e/lib/python3.8/site-packages/pydantic/v1/main.py", line 221, in __new__
    inferred = ModelField.infer(
  File "/home/wanchengquan/.conda/envs/character_e/lib/python3.8/site-packages/pydantic/v1/fields.py", line 506, in infer
    return cls(
  File "/home/wanchengquan/.conda/envs/character_e/lib/python3.8/site-packages/pydantic/v1/fields.py", line 436, in __init__
    self.prepare()
  File "/home/wanchengquan/.conda/envs/character_e/lib/python3.8/site-packages/pydantic/v1/fields.py", line 546, in prepare
    self._set_default_and_type()
  File "/home/wanchengquan/.conda/envs/character_e/lib/python3.8/site-packages/pydantic/v1/fields.py", line 570, in _set_default_and_type
    default_value = self.get_default()
  File "/home/wanchengquan/.conda/envs/character_e/lib/python3.8/site-packages/pydantic/v1/fields.py", line 439, in get_default
    return smart_deepcopy(self.default) if self.default_factory is None else self.default_factory()
  File "/home/wanchengquan/.conda/envs/character_e/lib/python3.8/site-packages/pydantic/v1/utils.py", line 693, in smart_deepcopy
    return deepcopy(obj)  # slowest way when we actually might need a deepcopy
  File "/home/wanchengquan/.conda/envs/character_e/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/wanchengquan/.conda/envs/character_e/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/wanchengquan/.conda/envs/character_e/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/wanchengquan/.conda/envs/character_e/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/wanchengquan/.conda/envs/character_e/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'classmethod' object

**Comment by guoqiaqia** [comment]
Have you solved this problem?

**Comment by ironworker4446** [comment]
bump - I'm having the same issue

**Comment by ironworker4446** [comment]
Found a workaround. Down grade langchain to version: 0.0.196
